NDefines.NDiplomacy.WARGOAL_JUSTIFICATION_OPINION_THRESHOLD = -20
NDefines.NDiplomacy.JUSTIFY_WAR_GOAL_TIME = 20
NDefines.NDiplomacy.PEACE_SCORE_PER_PASS = 5
NDefines.NCountry.JUSTIFY_WAR_GOAL_COST = 5
